fix: pipeline delete container on portainer

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -42,10 +42,18 @@ jobs:
 
       - name: Delete Portainer Container If Exists
         run: |
-          curl -X DELETE \
+          response=$(curl -X DELETE \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${{secrets.TOKEN}}" \
             https://${{secrets.PORTAINER_URI}}/api/endpoints/1/docker/containers/${{vars.CONTAINER_ID}}?force=true&v=0
+          )
+          
+          http_code=$(echo "$response" | awk '{print $NF}')
+          
+          if [[ ! "$http_code" =~ ^2[0-9][0-9]$ ]]; then
+            echo "HTTP response code is $http_code. Deployment failed."
+            exit 1
+          fi
 
       - name: Deploy to Portainer
         run: |
